# This is a basic workflow to help you get started with Actions

name: Add Google Analytics Header

# Controls when the workflow will run
on:
  push:
    branches: [ "gh-pages" ]
  pull_request:
    branches: [ "gh-pages" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Add Gtag
        run: sed -i 's/<!-- VideoJS -->/{<script async src="https://www.googletagmanager.com/gtag/js?id=G-D78BRDY5SL"></script><script>function gtag(){dataLayer.push(arguments)}window.dataLayer=window.dataLayer||[],gtag("js",new Date),gtag("config","G-D78BRDY5SL");</script>}/  index.html
        


